[package]
name = "narr_flow"
version = "0.0.1"
published-at = "0x0"
edition = "2024" 

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
narr_flow = "0x0"
sui = "0000000000000000000000000000000000000000000000000000000000000002" 