import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { SuiProvider } from "@/provider/suiProvider";
export const metadata: Metadata = {
  title: "Qidian on Sui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="pl-20 pr-20 bg-gray-100">
          <SuiProvider>
            <Header />
            <div className="min-h-[calc(100vh-160px)] flex flex-col pt-4 pb-4">
              {children}
            </div>
            <Footer />
          </SuiProvider>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
